nav:
  - index.md
  - Questionnaire: a._Questionnaire
  - Questions: b._Questions
  - Variables: c._Variables
  - Personnalisation: d._Personnalisation
  - Historique: e._Historique
  - Nomenclatures: f._Nomenclatures
  - Listes de codes: g._Listes_de_codes
  - Detail: h._Detail