  ui:
    enabled: true
    nameOverride: queen-ui
    replicaCount: 1
    image:
      repository: inseefr/queen
      tag: "X.Y.Z"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: queen.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - queen.example.com
    env:
      QUEEN_URL: https://queen.example.com
      authenticationType: NONE
