site_name: Atelier de Conception d'Enquêtes (Bowie)
site_url: https://inseefr.github.io/Bowie/
theme:
  name: material
  language: fr
  favicon : assets/bowie-zap-circle.png
  icon:
    logo: material/lightning-bolt-circle
    annotation: material/help-circle
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    # Light Mode
    - scheme: default
      toggle:
          icon: material/theme-light-dark
          name: Light mode
      primary: blue grey
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Dark mode
      primary: deep purple
      accent: cyan
  features:
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - navigation.instant.preview
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InseeFr/Bowie/
markdown_extensions:
  - attr_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      default_lang: 'r'
  - pymdownx.inlinehilite:
      style_plain_text: 'r'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
  - search